services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # network_mode: host est nécessaire pour que Scapy accède
    # aux vraies interfaces réseau de la machine hôte
    environment:
      PCAPS_ROOT: /app/pcaps
      MITRE_ROOT: /app/mitre
    network_mode: host
    volumes:
      - ./pcaps:/app/pcaps
      - ./mitre:/app/mitre
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      VITE_API_URL: http://localhost:5000
    network_mode: host
    depends_on:
      - backend
    restart: unless-stopped
